name: Java CI/CD Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 🔥 1️⃣ Installer common-lib dans le repo local Maven
      - name: Build & Install common-lib
        run: mvn -B clean install
        working-directory: common-lib

      # 2️⃣ Ensuite builder les autres services
      - name: Build api gateway
        run: mvn -B clean package
        working-directory: api-gateway

      - name: Build discovery service
        run: mvn -B clean package
        working-directory: discovery-service

      - name: Build school service
        run: mvn -B clean package
        working-directory: school-service

      - name: Build student service
        run: mvn -B clean package
        working-directory: student-service
