name: Java CI/CD Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build api gateway
      run: mvn -B package --file api-gateway/pom.xml
    - name: Build common
      run: mvn -B package --file common-lib/pom.xml
    - name: Build discovery service
      run: mvn -B package --file discovery-service/pom.xml
    - name: Build school service
      run: mvn -B package --file school-service/pom.xml
    - name: Build student service
      run: mvn -B package --file student-service/pom.xml
